apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: releaseward-dev
  labels:
    releaseward.dev/component: observability
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
