apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: releaseward-dev
  labels:
    releaseward.dev/component: observability
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
